name: Tests
on:
  pull_request:
  push:
    branches:
    - main
  schedule:
    # Weekly.
    - cron: "0 0 * * 0"

jobs:
  exercises:
    name: Check exercises
    runs-on: ubuntu-latest
    # idea from https://github.com/actions/starter-workflows/blob/master/ci/crystal.yml
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Run tests
        run: make test-exercises
      - name: Run generator tests
        run: make test-generator
